apiVersion: v1
kind: Pod
metadata:
  name: fwe
  labels:
    app: bcw-demo
spec:
  containers:
  - name: fwe
    image: ghcr.io/fsalamida/aws-iot-fleetwise-edge:feature-publish_container_image  
    env:
    - name: CAN_IF
      value: "vcan0"
    - name: FW_ENDPOINT
      value: "a1q6dgk6qorfqj-ats.iot.eu-central-1.amazonaws.com"
    - name: VEHICLE_NAME
      value: "vin200"
    - name: TRACE
      value: "off"
    volumeMounts:
    - name: private-key
      mountPath: "/etc/aws-iot-fleetwise/private-key.key"
      subPath: private-key.key
      readOnly: true
    - name: certificate
      mountPath: "/etc/aws-iot-fleetwise/certificate.pem"
      subPath: certificate.pem
      readOnly: true
  - name: vsim
    image: docker.io/library/vsim:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
      protocol: TCP
    env:
    - name: CAN_IF
      value: "vcan0"
    securityContext:
      privileged: true
      capabilities:
        add: ["CAP_NET_ADMIN"]
  volumes:
  - name: private-key
    secret:
      secretName: private-key
      optional: false 
  - name: certificate
    secret:
      secretName: certificate
      optional: false 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bcw-demo
  name: vsim-svc
spec:
  selector:
    app: bcw-demo
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 
    nodePort: 30000

