apiVersion: v1
kind: Pod
metadata:
  name: signalmeshpod
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: signalmesh
    image: signalmesh:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      capabilities:
        add: ["CAP_NET_ADMIN"]
    volumeMounts:
      - name: root
        mountPath: /root
  volumes:
    - name: root
      hostPath:
        path: /
